"""LLMOps core: plugin contract and host utilities (agent-agnostic)."""

from llmops_core.plugins import (
    ENTRY_POINT_GROUP,
    AgentHostContext,
    AgentPlugin,
    AgentRegistry,
    AgentShutdownHook,
    AgentStartupHook,
    PluginLoadError,
    PluginValidationError,
    PromptSeedDocument,
    coerce_plugin_object,
    load_plugin_from_entry_point,
    validate_plugin,
)
from llmops_core.prompts import (
    MongoPromptRepository,
    PromptRegistry,
    PromptRepository,
    PromptStatus,
    PromptVersionRecord,
    namespaced_prompt_label,
    seed_prompts_from_seeds,
)
from llmops_core.storage import (
    PostgresPoolManager,
    PostgresSettings,
    StorageBundle,
    StorageSettings,
    assert_embedding_dim,
    close_storage,
    ensure_pgvector_extension,
    open_storage,
    register_vector_types,
    storage_extras,
    vector_param,
)
from llmops_core.tracing import (
    LangfuseClientConfig,
    build_runnable_config,
    create_langfuse_callback_handler,
    create_langfuse_client,
    langfuse_run_config,
    merge_callbacks,
)

__all__ = [
    "ENTRY_POINT_GROUP",
    "AgentHostContext",
    "AgentPlugin",
    "AgentRegistry",
    "AgentShutdownHook",
    "AgentStartupHook",
    "build_runnable_config",
    "LangfuseClientConfig",
    "MongoPromptRepository",
    "PluginLoadError",
    "PluginValidationError",
    "PostgresPoolManager",
    "PostgresSettings",
    "PromptRepository",
    "PromptRegistry",
    "PromptSeedDocument",
    "PromptStatus",
    "PromptVersionRecord",
    "StorageBundle",
    "StorageSettings",
    "assert_embedding_dim",
    "close_storage",
    "coerce_plugin_object",
    "create_langfuse_callback_handler",
    "create_langfuse_client",
    "ensure_pgvector_extension",
    "langfuse_run_config",
    "load_plugin_from_entry_point",
    "merge_callbacks",
    "namespaced_prompt_label",
    "open_storage",
    "register_vector_types",
    "seed_prompts_from_seeds",
    "storage_extras",
    "validate_plugin",
    "vector_param",
]
